version: "3.9"
services:
  endpoint:
    build:
      context: .
      dockerfile: endpoint.Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - ForecastDbSettings__ConnectionString=mongodb://mongodb
      - ForecastDbSettings__DatabaseName=forecast
  job:
    build:
      context: WeatherForecast.GismeteoRipper
    environment:
      - WeatherForecastService__Endpoint=endpoint
      - WeatherForecastService__Port=5002
      - GismetioEndpoint=https://www.gismeteo.ru
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"