version: "3.9"
services:
  endpoint:
    build:
      context: .
      dockerfile: endpoint.Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - ForecastDbSettings__ConnectionString=mongodb://AzureDiamond:hunter2@mongodb
  job:
    build:
      context: WeatherForecast.GismeteoRipper
    environment:
      - WeatherForecastEndpoint=endpoint
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    ports:
      - "27018:27017"